### ISSUE TITLE
(Outdated) Linux Setup Guide has wrong command listed for installing node

### ISSUE THREAD

**Issue by OWL4C** [thepeacockproject/peacockprojectorg#17]
Under "Install Node.js" is `nvm install`, but it should be `nvm install node` to install the latest node
However, the new instructions should just be merged with the old ones, no?

**Comment by RDIL** [comment]
It's actually intentionally `nvm install`, because it should be picking up the exact Node version that Peacock is targeting from the `.nvmrc` and install that.

**Comment by OWL4C** [comment]
Interesting, then i guess the error was on my side. As the new linux instructions skip the entire nvm process in favor of a script, that would be irrelevant.
