### ISSUE TITLE
Chinese translation broken

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/peacockprojectorg#35]
After the roulette loc update, the Chinese translation has gone back to English.

![image](https://github.com/user-attachments/assets/4ad9f33c-b211-4774-a7fe-23742ffffab1)

**Comment by solderq35** [comment]
I think the translation issues broke in [this commit](https://github.com/thepeacockproject/peacockprojectorg/commit/7a2317715f9a56037419dac855c2090845c41ed2) mostly, see changes to `i18n/zh/docusaurus-plugin-content-docs...`

**Comment by RDIL** [comment]
Looks like it's because we enabled traditional chinese. Looking into fixing it

**Comment by RDIL** [comment]
Fixed
